 storage:
   name: bayescache.storage.classic

   backend:
     name: bayescache.storage.backend.dummy

   streaming:
     - name: bayescache.storage.streaming.stdout


 checkpoint_strategy:
   name: bayescache.storage.strategy.classic_checkpoint_strategy
