name: 'p3b3_mtcnn'


model:
  name: bayescache.models.mtcnn 


source:
  name: bayescache.sources.anon
  batch_size: 128
  num_workers: 4


commands:
  train:
    name: bayescache.commands.train_command
    epochs: 12
    log_frequency: 100

    optimizer:
      name: bayescache.optimizers.adadelta

    checkpoint:
      metric: 'val:loss'

  summary:
    name: bayescache.commands.summary_command


  visdom:
    name: bayescache.commands.vis_store_command
